### PR TITLE
mongo & elasticsearch sync

### LINKED ISSUE #37: mongo & elasticsearch sync

### PR DESCRIPTION
**Pull request by eyakauleva**
close #37

### CODE REVIEW

**Comment by eyakauleva** [comment]
> @eyakauleva what is the point of usage logstash instead of Kafka for MongoDB and Elasticsearch sync up?

@h1alexbel I don't use logstash for sync up but a nodejs app that is listening to mongodb replica set via mongo change streams and sends changes to elasticsearch if any detected. 
I didn't notice that kafka usage was required

**Comment by h1alexbel** [comment]
@eyakauleva you can investigate the ability to do this using Kafka, since it more flexible to use message broker for services decoupling

WDYT?

**Comment by eyakauleva** [comment]
@h1alexbel is it okay that than my app will work in total with 3 different kafka topics? Isn't that a lot?

**Comment by h1alexbel** [comment]
@eyakauleva it's ok, I believe

**Comment by eyakauleva** [comment]
@h1alexbel can you merge this PR? I will implement kafka usage in another one

**Pull request merged**
